sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: drfQ/vXmNvkVHCcS2W/yepG5dcd/gTK3H1U6g6nqwDyEkobkjnWUT5nSFh2nHrlXtv7rJ6/YF0mIdsdNX+b9GyTl+iqOJWQ/wmZqoujAj0LEwHqnTmVhpO4AXTFr+RchyPNBdOSYg/FXnVGpJ/gYfS/whmBRxWF27sHJsNIPz9ds9/N3JoQSgucccyxvKgVIo7qAfdl45Vk/uNYKKBcRd93tyjGKdOzgoLO6btfEw/9J1klaMG8uaxyN6qJLdEteLicrWXrUWhE8cdoYenyCLZCtETDXk3zRmfP+qrdI+tDZJmLz4Qf/hA6T+6Asp40/KGAK0h28R+9rIigp0j+auP9DXPlLBG/WRNzzdYgxk78Eon7uTMm56NWcoUsQOY40ntubYqktL98NBLFnMi7XD9SvUDNQneWvcGvDu6xqlT8OhHdLnhyBo3tX5Jvywlk1sz8MyQeNJhLuLOTNXYR0nuHuSiRvZOf2nvlf79IAx5VO/E+GOtppovxBpwoOIOBgXsxOuDBgJgVx6Iig4Z+/KwuusS94bJw7utzR1HaTpyBnk4vxnTHU3z7xRwHdKbgteZk9eKrTh1u5zX0Se9mlCEBZu5b5lwoMtB2bfiNjx4slt7nr0F98k4X8vzeYuPG0qMH/rUgv6alspi0jOkpgKXwj7Qes1ytg1/iYbvOsfm8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Zone-Policeman-88--a-close-range-study-of-the-Panama-canal-and-its-workers_4786
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy